export const appColors = {
  white: '#FFF',
  paleBeige: '#FAF8F5',
  beige: '#F9F4ED',
  orange: '#FF7B38',
  yellow: '#FFBF29',
  paleGreen: '#63BD82',
  lightGrey: '#b8b6bb',
  purple: '#8A3F91',
  black: '#000',
  blackOpacity: (opacity?: number) => `rgba(0, 0, 0, ${opacity ?? 0.5})`,
  orangeOpacity: (opacity?: number) => `rgba(255, 123, 56, ${opacity ?? 0.5})`,
  whiteOpacity: (opacity?: number) => `rgba(255, 255, 255, ${opacity ?? 0.5})`,
  transparent: 'transparent',
};
